"""add_image_source

Revision ID: 7cf569cf00be
Revises: e3823bd65b0b
Create Date: 2026-09-27 02:21:49.888391
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cf569cf00be'
down_revision: Union[str, None] = 'e3823bd65b0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('image_source', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'image_source')
    # ### end Alembic commands ###
