export default function TermsOfService() {
  return (
    <div className="static-page">
      <div className="static-doc-header">
        <div className="doc-meta"><strong>DOCUMENT ID</strong> DT-TOS-001</div>
        <div className="doc-meta"><strong>SUBJECT</strong> TERMS OF SERVICE</div>
        <div className="doc-meta"><strong>LAST UPDATED</strong> SEP 2026</div>
      </div>

      <div className="static-doc-content">
        <h2>1. Nature of Service</h2>
        <p>
          DigiTak is a news aggregation and summarization service. We collect
          publicly available financial news articles via RSS feeds and generate
          AI-powered summaries for informational purposes. All original
          content belongs to its respective publishers. We provide links to
          original sources for every article we summarize.
        </p>

        <h2>2. Not Financial Advice</h2>
        <p>
          Nothing on this website constitutes financial advice, investment
          recommendations, or trading signals. The summaries and market impact
          assessments are generated by artificial intelligence and may contain
          errors, omissions, or inaccuracies. You should always consult
          qualified financial professionals and verify information against
          original sources before making financial decisions.
        </p>

        <h2>3. Fair Use and Attribution</h2>
        <p>
          DigiTak operates under fair use principles. We summarize and
          transform news content rather than reproducing it in full. Every
          summary includes a direct link to the original article and credits
          the source publication. If you are a content publisher and have
          concerns about how your content is represented, please contact us.
        </p>

        <h2>4. AI-Generated Content</h2>
        <p>
          Summaries and market impact analyses are produced by automated
          systems using large language models. While we strive for accuracy,
          AI outputs can be incorrect, misleading, or incomplete. DigiTak
          makes no warranty regarding the accuracy or completeness of any
          AI-generated content.
        </p>

        <h2>5. Limitation of Liability</h2>
        <p>
          DigiTak and its operators shall not be held liable for any losses,
          damages, or costs arising from the use of information presented on
          this website, including but not limited to financial losses from
          trading or investment decisions influenced by content on this site.
        </p>

        <h2>6. Acceptable Use</h2>
        <p>
          You agree not to use this service to:
        </p>
        <ul>
          <li>Scrape or systematically download content for redistribution</li>
          <li>Overload our servers with automated requests</li>
          <li>Misrepresent DigiTak summaries as original reporting</li>
          <li>Use the service for any unlawful purpose</li>
        </ul>

        <h2>7. Modifications</h2>
        <p>
          We reserve the right to modify these terms at any time. Continued
          use of the service after changes constitutes acceptance of the
          updated terms.
        </p>

        <h2>8. Contact</h2>
        <p>
          For questions about these terms, please use the{" "}
          <a href="/contact">contact page</a>.
        </p>
      </div>
    </div>
  );
}
